# Generated by Django 4.2.30 on 2026-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0225_ticketmessage_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='unfreeze_time',
            field=models.DateTimeField(blank=True, help_text='Results are revealed after this time.', null=True, verbose_name='unfreeze time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('atcoder', 'AtCoder'), ('default', 'Default'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI (pre-2016)'), ('ioi16', 'IOI'), ('vnoj', 'VNOJ'), ('voi', 'VOI')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
    ]
