# Generated by Django 4.2.30 on 2026-05-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0225_ticketmessage_action.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_offline',
            field=models.BooleanField(default=False, help_text='Hide all submission verdicts, scores, and rankings from contestants.', verbose_name='offline contest'),
        ),
    ]
