# Generated by Django 4.2.30 on 2026-06-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0226_add_unfreeze_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('atcoder', 'AtCoder'), ('codeforces', 'Codeforces'), ('default', 'Default'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI (pre-2016)'), ('ioi16', 'IOI'), ('vnoj', 'VNOJ'), ('voi', 'VOI')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
    ]
