name: deploy
on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
jobs:
  deploy2qa:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Install cloudflared
        uses: cloudflare/cloudflared-action@v1
      - name: Run QA update script via Cloudflare Access SSH
        env:
          CLOUDFLARE_ACCESS_CLIENT_ID: ${{ secrets.QA_CLOUDFLARE_ACCESS_CLIENT_ID }}
          CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{ secrets.QA_CLOUDFLARE_ACCESS_CLIENT_SECRET }}
          VPS_HOST: ${{ secrets.QA_VPS_HOST }}
          VPS_USER: ${{ secrets.QA_VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.QA_VPS_SSH_KEY }}
          VPS_PORT: ${{ secrets.QA_VPS_PORT }}
        run: |
          mkdir -p ~/.ssh

          echo "$VPS_SSH_KEY" > ~/.ssh/qa_key
          chmod 600 ~/.ssh/qa_key

          cloudflared access ssh \
            --hostname "$VPS_HOST" \
            --url "ssh://$VPS_USER@$VPS_HOST:$VPS_PORT" \
            --identity-file ~/.ssh/qa_key \
            --command "/home/tloi/update_tloj.sh"

  deploy2prod:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'release'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Run PROD update script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            /home/tloi/update_tloj.sh
